# Generated by Django 4.0.5 on 2022-07-13 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='questiontitle',
        ),
    ]
